service: serverless-hello-world

provider:
  name: aws
  runtime: nodejs12.x

functions:
  helloWorld:
    handler: dist/index.handler
    name: serverless-hello-world
    description: Hello World Function
    memorySize: 512
    package:
      include:
        - dist/**

